### ISSUE TITLE
Collision with `pusher` gem

### ISSUE THREAD

**Issue by nhunzaker** [pusher/pusher-platform-ruby#15]
We'd like to use Chatkit on Rails project, however when we include `chatkit-server-ruby`, we hit the following error in `pusher-platform`:

```
~/ruby/gems/2.4.0/gems/pusher-platform-0.6.0/lib/pusher-platform/common.rb:2:
in `<module:Pusher>': superclass mismatch for class Error (TypeError)
```

I think this is because of a collision between `Pusher::Error` on both gems:

**pusher-platform**
https://github.com/pusher/pusher-platform-ruby/blob/b077a70b1f911e90641bc6ec5406a5febb76f55f/lib/pusher-platform/common.rb

**pusher**
https://github.com/pusher/pusher-http-ruby/blob/adf04980682264050e70b99dd39dc8b82af2390a/lib/pusher.rb#L18

Is this correct, and do you know of a workaround?

**Comment by hamchapman** [comment]
Sorry for the slow response!

This does look like a problem. I'll make sure this is fixed in the next release, which should hopefully be quite soon!

**Comment by nhunzaker** [comment]
Awesome. Thank you!
