### ISSUE TITLE
ErrorResponse properties are nested in a hash under error_description instead of in their own attributes

### ISSUE THREAD

**Issue by CarlLooksUp** [pusher/pusher-platform-ruby#19]
### What?
ErrorResponse properties (error, error_uri, error_description) are nested in a hash under error_description instead of in their own attributes.

### Suggested improvements
Change invocation of ErrorResponse constructor to unpack data across the class fields.

----

CC @pusher/sigsdk

**Comment by hamchapman** [comment]
Hey @CarlLooksUp where are you seeing this happen?

As far as I can see from the code it looks like it should be assigning attributes correctly

**Comment by hamchapman** [comment]
Fixed in #20 - thanks @CarlLooksUp !

I'll publish a new version right now 👍
